const multer = require("multer");
const router = require("express").Router();
const userControllers = require("../controllers/user.controllers.js");
const storage = require("../utils/storage.js");
const verifyToken = require("../utils/verifyToken.js");
const upload = multer({ storage });
router.post("/register", upload.single("image"), userControllers.registerUser);
router.post("/login", userControllers.loginUser);
router.get("/validate-user", verifyToken, userControllers.validateUser);
router.get("/get-my-info", verifyToken, userControllers.getMyInfo);
router.post("/logout", userControllers.logoutUser);
module.exports = router;
